#!/bin/sh

# Get list of staged files
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM)

# Run lint and format
yarn run lint:fix && yarn run format:fix

# Re-add only the files that were originally staged
echo "$STAGED_FILES" | xargs -r git add